### ISSUE TITLE
Run react native ios

### ISSUE THREAD

**Issue by cakiem8x** [viettranx/tracking-location-socketio#1]
** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock build/Build/Intermediates/tracking_location.build/Debug-iphonesimulator/tracking_location.build/Script-B7E92F0516ACA9B84E35EB65.sh

(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/tracking_location.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/tracking_location.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by jerryheir** [comment]
There is something wrong in your Info.plist. you probably made a change somewhere there. Try removing those changes

**Comment by viettranx** [comment]
Since this example with React Native was out-dated version, some of libraries (react-native-maps) have some updates and we have to follow their new instruction to re-install it.
